spring:
  datasource:
    url: jdbc:h2:file:./data/caba_pro  # Guarda en archivo
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # Actualiza sin borrar datos
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: 8080

# Ruta de almacenamiento de fotos de perfil de Ã¡rbitros
caba-pro:
  fotos-perfil-path: uploads/perfiles/
